In [53]:
import pandas as pd
df = pd.read_csv('/content/titanic.csv')
df.head(1)

,passengerid,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,1,"Allen, Miss. Elisabeth Walton",female,29.0,0,0,24160,211.3375,B5,S

In [54]:
null_df = df.isnull().sum()
print(null_df)

passengerid       0
pclass            0
survived          0
name              0
sex               0
age             263
sibsp             0
parch             0
ticket            0
fare              1
cabin          1014
embarked          2
dtype: int64

In [55]:
df['age'].fillna(df['age'].mean(), inplace=True)
df['fare'].fillna(df['fare'].mode()[0], inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
# df.drop(['cabin'], axis=1, inplace=True)
null_df = df.isnull().sum()
print(null_df)

passengerid       0
pclass            0
survived          0
name              0
sex               0
age               0
sibsp             0
parch             0
ticket            0
fare              0
cabin          1014
embarked          0
dtype: int64

In [56]:
df = pd.get_dummies(df,columns=['sex','embarked'])
df.head(1)

,passengerid,pclass,survived,name,age,sibsp,parch,ticket,fare,cabin,sex_female,sex_male,embarked_C,embarked_Q,embarked_S
0,1,1,1,"Allen, Miss. Elisabeth Walton",29.0,0,0,24160,211.3375,B5,True,False,False,False,True

In [57]:
df.drop(['name','ticket','cabin'],axis=1,inplace=True)
df.head()

,passengerid,pclass,survived,age,sibsp,parch,fare,sex_female,sex_male,embarked_C,embarked_Q,embarked_S
0,1,1,1,29.0000,0,0,211.3375,True,False,False,False,True
1,2,1,1,0.9167,1,2,151.5500,False,True,False,False,True
2,3,1,0,2.0000,1,2,151.5500,True,False,False,False,True
3,4,1,0,30.0000,1,2,151.5500,False,True,False,False,True
4,5,1,0,25.0000,1,2,151.5500,True,False,False,False,True

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


x=df.drop(['survived'],axis=1)
y=df['survived']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LogisticRegression(max_iter = 2000)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))

Accuracy: 0.7709923664122137
Confusion Matrix:
 [[126  18]
 [ 42  76]]
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.88      0.81       144
           1       0.81      0.64      0.72       118

    accuracy                           0.77       262
   macro avg       0.78      0.76      0.76       262
weighted avg       0.78      0.77      0.77       262

In [ ]:
# GUI
data=pd.read_csv('titanic.csv')
import tkinter as tk
from tkinter import ttk
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
root = tk.Tk()
root.title(" Rohitkumar ")
report = classification_report(y_test, model.predict(x_test), output_dict=True)
report_text = pd.DataFrame(report).transpose().round(2).to_string()
text = tk.Text(root, height=10, width=60)
text.insert(tk.END, report_text)
text.pack()
gender_label = ttk.Label(root, text="Select Gender:")
gender_label.pack(pady=5)
gender = ttk.Combobox(root, values=["male", "female"])
gender.pack(pady=5)
pclass_label = ttk.Label(root, text="Select Pclass:")
pclass_label.pack(pady=5)
pclass = ttk.Combobox(root, values=[1, 2, 3])
pclass.pack(pady=5)
def show_survivors():
    filtered = data[(data['sex'] == gender.get()) & (data['pclass'] == int(pclass.get())) & (data['survived'] == 1)]
    result_text = f"Survivors: {len(filtered)}"
    result_label.config(text=result_text)
button = ttk.Button(root, text="Show Survivors", command=show_survivors)
button.pack(pady=10)
result_label = ttk.Label(root, text="")
result_label.pack(pady=5)
root.mainloop()